Repository DaITssu/daitssu-crawl, pull requests merged in 2023-10, with the labels that each got.

#44 fix: update .gitignore
  .gitignore
Labels: documentation

#41 [#40] 스마트 캠퍼스 크롤링 코드 db 연결 오류 수정
  smart_campus.py
Labels: 스마트캠퍼스

#47 Feat/ci cd
  .github/workflows/deploy-ecs.yml
  .github/workflows/deploy-lambda.yml
  Dockerfile
  computer.py
  fun_system.py
  requirements.txt
  server.py
  ssu_catch.py
  task-definition.json
Labels: lambda

#42 [#34] 컴퓨터 학부 공지사항, 슈케치 본문 저장 방식 변경
  computer.py
  ssu_catch.py
Labels: 학과 공지사항, 슈캐치 공지사항

#46 [#45] sync category string
  computer.py
  ssu_catch.py
Labels: 학과 공지사항, 슈캐치 공지사항
