Repository DaITssu/daitssu-crawl, pull requests merged in 2023-09, with the labels that each got.

#17 [#10] SSU:Catch 공지사항 크롤링 코드 db ORM 작성.
  ssu_catch.py
Labels: 슈캐치 공지사항

#22 [#21] 컴퓨터학부 공지사항 크롤링 코드 작성
  departments.py
Labels: 학과 공지사항

#16 [#1]: 펀시스템 크롤링 코드&DB연결 코드 추가
  fun_system.py
Labels: 펀시스템

#23 [#14] orm이용한 스마트캠퍼스 크롤링
  smart_campus.py
Labels: 스마트캠퍼스

#25 [#24] 스마트캠퍼스 auth token 발급 로직 추가
  auth_token.py
  lambda_function.py
Labels: 스마트캠퍼스

#27 [#26] import 및 드라이버 명시 수정
  departments.py
  fun_system.py
  smart_campus.py
  ssu_catch.py
Labels: bug

#36 [#31] lambda_handler에 스마트캠퍼스 연결
  lambda_function.py
  smart_campus.py
Labels: 스마트캠퍼스
