Repository DaITssu/daitssu-crawl, pull requests merged in 2023-11, with the labels that each got.

#51 [#50] s3 authentication 오류를 해결합니다.
  computer.py
  ssu_catch.py
Labels: bug, 학과 공지사항, 슈캐치 공지사항

#55 [fix] lxml 의존성 문제 해결
  requirements.txt
Labels: bug

#53 [#52] 에러 핸들링 코드 수정
  computer.py
  ssu_catch.py
Labels: bug, 학과 공지사항, 슈캐치 공지사항

#58 [#57] 중복 게시글 크롤링 수정 및 코드 리팩터링
  computer.py
  control_db.py
  notification.py
  ssu_catch.py
Labels: enhancement, 학과 공지사항, 슈캐치 공지사항

#59 [#56] s3 파일 저장 경로 수정
  computer.py
  ssu_catch.py
Labels: bug, 학과 공지사항, 슈캐치 공지사항

#35 [feat] ai융합학부 공지사항 크롤링 코드 추가
  ai.py
Labels: enhancement, 학과 공지사항
