Repository DaITssu/daitssu-crawl, pull requests merged in 2023-08, with the labels that each got.

#8 feat: fun_system 크롤링 코드 추가
  fun_system.py
Labels: 펀시스템

#4 [#3] 수강중인 강의, 강의별 출결 상태, 과제 및 강의 기한 확인
  departments.py
  fun_system.py
  lambda_function.py
  smart_campus.py
  ssu_catch.py
Labels: 스마트캠퍼스

#5 [#2] SSU:Catch 공지사항 크롤링 코드 작성
  ssu_catch.py
Labels: 슈캐치 공지사항

#9 [#1] 펀시스템 프로그램 크롤링 코드 추가
  fun_system.py
Labels: 펀시스템

#11 [#3] 과목코드에 따라 색상코드 부여하는 코드 추가
  smart_campus.py
Labels: 스마트캠퍼스

#13 [#12] lambda_handler의 body 처리 방식 변경
  .github/pull_request_template.md
  lambda_function.py
Labels: bug

#18 [#3] 스마트 캠퍼스에서 받아온 데이터 db에 삽입
  smart_campus.py
Labels: 스마트캠퍼스
